# --- Serving options --- #

# url is the full website URL
# baseurl is the website's URL without the hostname

# If you are building a simple GitHub user page (username.github.io) then use these settings:
url: "http://sermons.seanho.com"
baseurl: ""

# If you are building a GitHub project page then use these settings:
#url: "http://daattali.github.io/beautiful-jekyll"
#baseurl: "/beautiful-jekyll"

# Of course don't forget to change the username and projectname to YOUR username and project

# Name of website
title: Sermons by Sean

# Short description of your site
description: Archive of sermons with slides

# --- Navigation bar options --- #

# Image to show in the navigation bar - image must be a square (width = height)
# Remove this parameter if you don't want an image in the navbar
avatar: "/img/cross.svg"

# List of links in the navigation bar
navbar-links:
  Home: ""
  Github: "https://github.com/sermons"
  About me: "http://seanho.com"

# --- Footer options --- #

# Change all these values or delete the ones you don't want.
# Important: you must keep the "name" parameter, everything else you can remove
author:
  name: Sean Ho
  email: "sermons@seanho.com"
  facebook: seanho00
  github: seanho00
  twitter: seanho00
  linkedin: seanho00
 
# Select which links to show in the footer
footer-links-active:
  rss: true
  facebook: true
  email: true
  twitter: true
  github: true
  linkedin: true

# How to display the link to the website in the footer
# Remove this if you don't want a link in the footer
url-pretty: "sermons.seanho.com"  # eg. "deanattali.com/beautiful-jekyll"

# --- Misc --- #

# Fill in your Disqus shortname (NOT the userid) if you want to support Disqus comments
#disqus: ""

# Fill in your Google Analytics ID to track your website using GA
#google_analytics: "UA-59820529-1"

# --- Don't need to touch anything below here (but you can if you want) --- #

# Output options (more information on Jekyll's site)
timezone: "America/Vancouver"
markdown: kramdown
highlighter: rouge
permalink: /:year-:title/
paginate: 5

# Default YAML values (more information on Jekyll's site)
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true  # add comments to all blog posts 
      show-share: true # add sharing buttons to all blog posts
  -
    scope:
      path: "" # all files
    values:
      layout: "page"

# Exclude these files from production site
exclude:
  - CNAME
  - LICENSE
  - README.md
